M48
; DRILL file KiCad 10.0.1 date 2026-06-06T14:49:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-06T14:49:54-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X102.2Y-74.0
X102.2Y-134.0
X192.2Y-74.0
X192.2Y-134.0
T2
X118.77Y-75.0
M30
